# Generated by Django 3.0.4 on 2020-03-29 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_countryofprod'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('T', 'WATCH TRAILER'), ('W', 'WATCH MOVIE'), ('D', 'DOWNLOAD LINK')], max_length=1)),
                ('movielink', models.URLField()),
                ('trailerlink', models.URLField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_watch_link', to='movie.Movie')),
            ],
        ),
    ]
