# Generated by Django 3.0.4 on 2020-03-29 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_movielinks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieLinks',
            new_name='MovieLink',
        ),
    ]
