# Generated by Django 3.0.4 on 2020-03-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_remove_movielink_movielink'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailerLink',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
